version: "2"
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: 'channel/eslint-7'
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - dist/
  - "**/node_modules/"
  - "**/*.d.ts"
