version: 2.1
orbs:
  node: circleci/node@4.7

executors:
  default:
    docker: 
      - image: node:current-buster-slim

jobs:
  build:
    executor: default
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  release:
    executor: default
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: .
      - run: npx semantic-release
      - run: npm run deploy-storybook -- --ci

  test:
    executor: default
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:ci

workflows:
  version: 2
  default:
    jobs:
      - test
      - build:
          requires:
            - test
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
